import type { AreaDefinition, WorldDefinition } from '../domain/World.js'; import {interaction as i,portal as p,room} from './WorldFactory.js';
// Master scenario 705~1022: 비는 그쳐 있고 창백한 햇빛이 돌바닥에 내려앉아 있다 — GR-2 야외는 'rain'이 아니다.
const sub=(a:AreaDefinition,s:string):AreaDefinition=>({...a,subtitle:s});
export const chapter2World:WorldDefinition={areas:{
 // 광장 방위(원문 732): 북=블랙우드 성, 동=상점가, 서=여관 거리, 남=시청과 주거지. 화면 상단=북 규약.
 villageSquare:sub(room('villageSquare','Ashvale 중앙 광장','bg.villageSquare',[p('sq.gate',600,20,'townGate','북 · 블랙우드 성',undefined,{x:140,y:600}),p('sq.market',1180,300,'marketStreet','동 · 상점가'),p('sq.inn',30,300,'innGroundFloor','서 · 여관 거리',undefined,{x:160,y:600}),p('sq.hall',600,590,'townHallExterior','남 · 시청과 주거지','innFireStarted',{x:635,y:120})],[i('square.statue',500,330,'목 꺾인 여인의 석상'),i('square.fountain',600,330,'마른 분수'),i('square.board',860,180,'낡은 게시판'),i('square.candle',340,570,'봉헌 촛대'),i('square.signNorth',700,60,'북쪽 표지판'),i('square.signEast',1090,320,'동쪽 표지판'),i('square.signWest',130,320,'서쪽 표지판'),i('square.signSouth',700,600,'남쪽 표지판')],'silence'),'그친 비, 창백한 햇빛'),
 marketStreet:sub(room('marketStreet','상점가 · 잡화점','bg.marketStreet',[p('market.back',20,560,'villageSquare','광장',undefined,{x:1120,y:350}),p('market.alley',1200,560,'marketAlley','뒷골목')],[i('market.ledger',350,250,'계산대 위의 장부'),i('market.shelf',760,260,'진열대와 선반')],'silence'),'끼익거리는 낡은 간판들'),
 marketAlley:sub(room('marketAlley','상점가 뒷골목','bg.marketAlley',[p('alley.back',20,560,'marketStreet','잡화점'),p('alley.house',1200,560,'houseExterior','반쯤 열린 폐가','hollowSighted')],[i('alley.mirror',650,250,'금 간 거울')],'silence',{enemyAssetId:'enemy.hollow',spawn:{x:700,y:170},speed:175,catchTitle:'섬뜩한 손길',catchBody:'뒤에서 뻗어온 손이 옷깃을 낚아챈다. 온 힘을 다해 뿌리치고 뒷걸음질 친다.'}),'젖은 돌바닥과 빨라지는 발소리'),
 houseExterior:sub(room('houseExterior','모리스 폐가 현관','bg.houseExterior',[p('house.out',20,560,'marketAlley','골목'),p('house.in',1200,560,'houseInterior','폐가 안','hollowSighted')],[i('house.bar',650,300,'움푹 들어간 나무 문')],'silence'),'모퉁이를 세 번 꺾은 뒤'),
 houseInterior:sub(room('houseInterior','모리스 폐가 내부','bg.houseInterior',[p('house.exit',20,560,'houseExterior','현관')],[i('house.hide',420,420,'문에 빗장을 지르고 숨죽이기'),i('house.diary',780,280,'거실 서랍장 위의 가죽 일기장','house.diary','hidSuccessfully')],'cabin'),'곰팡이 냄새와 쇠비린내'),
 innGroundFloor:sub(room('innGroundFloor','The Black Lamb · 1층','bg.innGroundFloor',[p('inn.back',20,560,'villageSquare','광장',undefined,{x:160,y:350}),p('inn.cellar',1200,560,'innCellar','지하 저장고','blackLambClueKnown')],[i('inn.board',420,260,'검은 양의 간판과 카운터'),i('inn.candle',760,280,'봉헌 촛대')],'cabin'),'술 냄새와 오래된 피 냄새'),
 innCellar:sub(room('innCellar','여관 지하 저장고','bg.innCellar',[p('wine.back',20,560,'innGroundFloor','1층'),p('wine.escape',1200,560,'innCellarEscape','작은 통풍창','innFireStarted')],[i('wine.hint',570,410,'저장고의 약도'),...['I','II','III','IV','V','VI'].map((n,k)=>i(`wine.shelf${n}`,170+k*165,190,`와인 선반 ${n}`)),i('wine.serpentBox',1030,330,'뱀이 새겨진 나무 상자','wine.serpentBox','wineOrderSolved'),i('escape.lamp',300,560,'램프를 바닥에 내리치기','escape.lamp','ironGateKeyTaken')],'silence'),'낮고 비좁은 저장고'),
 innCellarEscape:sub(room('innCellarEscape','여관 환풍구 통로','bg.innCellarEscape',[p('escape.out',1200,560,'villageSquare','뒷골목으로 탈출',undefined,{x:170,y:430})],[],'chase',{enemyAssetId:'enemy.maw',spawn:{x:1080,y:360},speed:195,catchTitle:'닫히는 턱',catchBody:'거대한 턱이 스치듯 닫힌다. 반사적으로 몸을 굴려 환풍구 쪽 어둠 속으로 다시 붙는다.',onEnter:true}),'등 뒤에서 번지는 불길'),
 townHallExterior:sub(room('townHallExterior','Ashvale 시청 외부 · 광장 남쪽','bg.townHallExterior',[p('civic.back',20,560,'villageSquare','광장',undefined,{x:635,y:530}),p('civic.in',1200,560,'townHallInterior','시청 계단')],[],'chase',{enemyAssetId:'enemy.hollow',spawn:{x:640,y:430},speed:180,catchTitle:'숨을 곳 없는 광장',catchBody:'회색 손이 어깨를 훑고 지나간다. 몸을 비틀어 빠져나와 다시 시청 계단 쪽으로 방향을 잡는다.',onEnter:true}),'숨을 곳 없는 횡단'),
 townHallInterior:sub(room('townHallInterior','시청 내부 홀','bg.townHallInterior',[p('hall2.back',20,560,'townHallExterior','밖'),p('hall2.records',1200,560,'townHallRecords','기록보관실')],[i('civic.thud',200,430,'빗장을 지른 정문'),i('civic.pillars',420,260,'이름이 새겨진 네 기둥'),i('civic.coal',800,430,'일기장의 빈 페이지와 숯')],'cabin'),'긴 회의 탁자와 흩어진 서류'),
 townHallRecords:sub(room('townHallRecords','시청 기록보관실','bg.townHallRecords',[p('records.back',20,560,'townHallInterior','시청 홀'),p('records.kitchen',1180,560,'villageSquare','부엌 쪽 뒷문','fourNamesKnown',{x:560,y:520})],[i('civic.record',600,400,'붉은 줄의 기록'),
  // 명패는 비문으로만 식별되고, 배치 순서는 정답(엘리노어→아이작→마사→토머스)과 다르게 섞여 있다.
  ...([['martha','그녀가 처음 입을 열었다'],['thomas','그가 마지막으로 기록했다'],['eleanor','그녀가 처음 쓰러졌다'],['isaac','그가 처음 되살렸다']] as const).map(([n,t],k)=>i(`civic.name.${n}`,260+k*230,220,`명패 — ${t}`))],'silence'),'붉은 줄이 그어진 명부'),
 townGate:sub(room('townGate','Ashvale 외성문','bg.townGate',[p('gate2.back',20,560,'villageSquare','광장',undefined,{x:635,y:170}),p('gate2.forward',1200,560,'villageChaseFinal','Blackwood 길','nameSlotSolved')],[i('gate2.slot',620,280,'△ ○ ✠ 석판'),
  // 원문 1009~1010: 석판 옆의 네 석상 — 쓰러진 / 무릎 꿇은 / 입을 벌린 / 펜을 쥔.
  ...([['fallen','쓰러진 석상'],['kneeling','무릎 꿇은 석상'],['mouth','입을 벌린 석상'],['pen','펜을 쥔 석상']] as const).map(([k,l],n)=>i(`gate2.statue.${k}`,440+n*120,420,l,undefined,'gateTried'))],'silence'),'언덕 아래 돌과 철의 문'),
 villageChaseFinal:sub(room('villageChaseFinal','마을 기상 · 최종 접근','bg.villageChaseFinal',[],[i('chase2.howl',720,240,'뒤에서 들리는 울부짖음'),i('chase2.gate',1080,340,'Blackwood 성문으로')],'chase',{enemyAssetId:'enemy.hollow',spawn:{x:340,y:260},speed:185,catchTitle:'흔들리는 시야',catchBody:'차가운 손아귀가 팔을 붙든다. 비명과 함께 뿌리치고 다시 성문 쪽으로 내달린다.',onEnter:true}),'여관의 불길을 보고 깨어난 것들'),
 ending2:room('ending2','CHAPTER 2 COMPLETE','bg.gr2Ending',[],[]),
 // placeholders required by the shared AreaId record; merged with the other worlds at runtime
} as WorldDefinition['areas']};
