import type { WorldDefinition } from '../domain/World.js'; import {interaction as i,portal as p,room} from './WorldFactory.js';
export const chapter2World:WorldDefinition={areas:{
 villageSquare:room('villageSquare','Ashvale 중앙 광장','bg.villageSquare',[p('sq.market',1200,500,'marketStreet','상점가'),p('sq.inn',600,600,'innGroundFloor','The Black Lamb 여관'),p('sq.hall',600,20,'townHallExterior','시청'),p('sq.gate',1200,150,'townGate','Blackwood 성 방향')],[i('square.statue',260,280,'목 꺾인 석상'),i('square.fountain',580,320,'마른 분수'),i('square.board',900,260,'게시판'),i('square.candle',340,570,'봉헌 촛대')],'rain'),
 marketStreet:room('marketStreet','상점가 · 잡화점','bg.marketStreet',[p('market.back',20,560,'villageSquare','광장',undefined,{x:1140,y:550}),p('market.alley',1200,560,'marketAlley','뒷골목')],[i('market.ledger',350,250,'잡화점 장부'),i('market.shelf',760,260,'진열대')],'rain'),
 marketAlley:room('marketAlley','상점가 뒷골목','bg.marketAlley',[p('alley.back',20,560,'marketStreet','잡화점'),p('alley.house',1200,560,'houseExterior','폐가','hollowSighted')],[i('alley.mirror',650,250,'금 간 거울')],'rain',{enemyAssetId:'enemy.hollow',spawn:{x:700,y:170},speed:175,catchTitle:'섬뜩한 손길',catchBody:'뒤에서 뻗어온 손이 옷깃을 낚아챈다. 온 힘을 다해 뿌리치고 뒷걸음질 친다.'}),
 houseExterior:room('houseExterior','모리스 폐가 현관','bg.houseExterior',[p('house.out',20,560,'marketAlley','골목'),p('house.in',1200,560,'houseInterior','폐가 안','hollowSighted')],[i('house.bar',650,300,'부푼 빗장')],'rain'),
 houseInterior:room('houseInterior','모리스 폐가 내부','bg.houseInterior',[p('house.exit',20,560,'houseExterior','현관')],[i('house.hide',420,420,'침대 밑에 숨기'),i('house.diary',780,280,'협탁의 일기','house.diary','hidSuccessfully')],'cabin'),
 innGroundFloor:room('innGroundFloor','The Black Lamb · 1층','bg.innGroundFloor',[p('inn.back',20,560,'villageSquare','광장',undefined,{x:635,y:520}),p('inn.cellar',1200,560,'innCellar','지하 저장고','blackLambClueKnown')],[i('inn.board',420,260,'여관 게시판'),i('inn.candle',760,280,'봉헌 촛대')],'cabin'),
 innCellar:room('innCellar','여관 지하 저장고','bg.innCellar',[p('wine.back',20,560,'innGroundFloor','1층'),p('wine.escape',1200,560,'innCellarEscape','환풍구','ironGateKeyTaken')],[i('wine.hint',570,410,'중앙 약도'),...['I','II','III','IV','V','VI'].map((n,k)=>i(`wine.shelf${n}`,170+k*165,190,`와인 선반 ${n}`)),i('wine.serpentBox',1030,330,'뱀 나무 상자','wine.serpentBox','wineOrderSolved')],'silence'),
 innCellarEscape:room('innCellarEscape','여관 환풍구 통로','bg.innCellarEscape',[p('escape.out',1200,560,'villageSquare','광장으로 탈출')],[i('escape.lamp',620,330,'떨어진 등잔')],'chase',{enemyAssetId:'enemy.maw',spawn:{x:1080,y:360},speed:195,catchTitle:'닫히는 턱',catchBody:'거대한 턱이 스치듯 닫힌다. 반사적으로 몸을 굴려 환풍구 쪽 어둠 속으로 다시 붙는다.',onEnter:true}),
 townHallExterior:room('townHallExterior','Ashvale 시청 외부','bg.townHallExterior',[p('civic.back',20,560,'villageSquare','광장',undefined,{x:635,y:140}),p('civic.in',1200,560,'townHallInterior','시청 내부')],[i('civic.thud',650,260,'벽 너머 충돌음')],'rain'),
 townHallInterior:room('townHallInterior','시청 내부 홀','bg.townHallInterior',[p('hall2.back',20,560,'townHallExterior','밖'),p('hall2.records',1200,560,'townHallRecords','기록보관실')],[i('civic.pillars',420,260,'네 기둥'),i('civic.coal',800,430,'숯 흔적')],'cabin'),
 townHallRecords:room('townHallRecords','시청 기록보관실','bg.townHallRecords',[p('records.back',20,560,'townHallInterior','시청 홀')],[i('civic.record',600,400,'붉은 줄의 기록'),...['eleanor','isaac','martha','thomas'].map((n,k)=>i(`civic.name.${n}`,260+k*230,220,`${k+1}번째 명패`))],'silence'),
 townGate:room('townGate','Ashvale 마을 성문','bg.townGate',[p('gate2.back',20,560,'villageSquare','광장',undefined,{x:1140,y:220}),p('gate2.forward',1200,560,'villageChaseFinal','Blackwood 길','nameSlotSolved')],[i('gate2.slot',620,280,'△ ○ ✠ 석판')],'rain'),
 villageChaseFinal:room('villageChaseFinal','마을 기상 · 최종 접근','bg.villageChaseFinal',[],[i('chase2.gate',1080,340,'Blackwood 성문으로')],'chase',{enemyAssetId:'enemy.hollow',spawn:{x:340,y:260},speed:185,catchTitle:'흔들리는 시야',catchBody:'차가운 손아귀가 팔을 붙든다. 비명과 함께 뿌리치고 다시 성문 쪽으로 내달린다.',onEnter:true}),
 ending2:room('ending2','CHAPTER 2 COMPLETE','bg.gr2Ending',[],[]),
 // placeholders required by the shared AreaId record; merged with the other worlds at runtime
} as WorldDefinition['areas']};
