import type { WorldDefinition } from '../domain/World.js'; import {interaction as i,portal as p,room} from './WorldFactory.js';
export const chapter3World:WorldDefinition={areas:{
 castleGateChain:room('castleGateChain','Blackwood Castle · 청동 성문','bg.castleGateChain',[p('gate3.in',1200,560,'greatHall','대현관','gateSealed')],[i('gate3.chain',500,300,'성문 체인')],'rain'),
 greatHall:room('greatHall','Blackwood Castle · 대현관','bg.greatHall',[p('hall.dining',1200,180,'diningRoom','식당'),p('hall.parlor',1200,500,'parlor','응접실'),p('hall.study',600,20,'office2F','2층 집무실')],[i('hall.portrait',400,250,'엘리노어 초상화'),i('hall.footprints',700,450,'젖은 발자국'),i('hall.candle',930,280,'봉헌 촛대')],'cabin'),
 diningRoom:room('diningRoom','성의 식당','bg.diningRoom',[p('dining.back',20,560,'greatHall','대현관')],[i('dining.embers',400,240,'따뜻한 재'),i('dining.table',760,350,'차려진 식탁')],'cabin'),
 parlor:room('parlor','성의 응접실','bg.parlor',[p('parlor.back',20,560,'greatHall','대현관')],[i('parlor.mannequin',420,300,'창백한 마네킹'),i('parlor.piano',800,280,'열린 피아노')],'silence'),
 office2F:room('office2F','2층 집무실','bg.office2F',[p('study.back',20,560,'greatHall','대현관'),p('study.down',1200,560,'corridorDescent','나선 계단','reginaldEncountered')],[i('study.journal',430,280,'레지널드의 일지'),i('study.reginald',850,280,'커튼 뒤 인기척','study.reginald','journalRead')],'cabin'),
 corridorDescent:room('corridorDescent','나선 계단 하강','bg.corridorDescent',[p('descent.down',1200,560,'greatHallSealed','봉쇄된 대현관')],[i('descent.doors',620,280,'열리는 문들')],'chase',{enemyAssetId:'character.reginald',spawn:{x:200,y:260},speed:180,catchTitle:'회색 손',catchBody:'계단 틈으로 뻗어 나온 손이 발목을 붙든다. 필사적으로 떨쳐내고 다시 계단을 구른다.',onEnter:true}),
 greatHallSealed:room('greatHallSealed','대현관 · 봉쇄됨','bg.greatHallSealed',[p('sealed.down',1200,560,'serviceCorridorB1','서비스 복도','serviceDoorFound')],[i('sealed.frontDoor',400,280,'안개 낀 정문'),i('sealed.serviceDoor',850,300,'초상화 아래 틈')],'chase',{enemyAssetId:'character.reginald',spawn:{x:640,y:180},speed:190,catchTitle:'레지널드의 손짓',catchBody:'실루엣이 성큼 다가와 어깨를 짓누른다. 몸을 비틀어 벽 쪽 그림자 속으로 미끄러진다.',onEnter:true}),
 serviceCorridorB1:room('serviceCorridorB1','B1 서비스 복도','bg.serviceCorridorB1',[p('service.down',1200,560,'laboratoryB2','B2 실험실','silenceNoted')],[i('service.silence',620,300,'푸른 횃불 아래 침묵')],'silence'),
 laboratoryB2:room('laboratoryB2','B2 실험실','bg.laboratoryB2',[p('lab.ritual',1200,560,'ritualChamber','의식실','eleanorConfirmed')],[i('lab.tubes',300,260,'유리관'),i('lab.pedestal',620,300,'빈 받침대'),i('lab.eleanor',900,280,'엘리노어의 흔적')],'silence'),
 ritualChamber:room('ritualChamber','최종 의식실','bg.ritualChamber',[],[i('ritual.approach',420,350,'삼중 링에 접근'),i('ritual.kneel',650,350,'제단 앞에 무릎 꿇기','ritual.kneel','ritualEntered'),i('ritual.dial',820,350,'저항하며 다이얼 돌리기','ritual.dial','boxOpened'),i('ritual.witness',1050,350,'열린 문을 바라보기','ritual.witness','boxOpened')],'silence'),
 ending3:room('ending3','GRAIL · END','bg.gr3Ending',[],[]),
} as WorldDefinition['areas']};
